### ISSUE TITLE
Warning log file

### ISSUE THREAD

**Issue by iObi** [Cadsters/acv-hass-component#14]
Log is showing the following warning since 2012.12.1

(<class 'custom_components.acv.sensor.TomorrowWasteSensor'>) implements device_state_attributes. Please report it to the custom component author.
(<class 'custom_components.acv.sensor.WasteTypeSensor'>) implements device_state_attributes. Please report it to the custom component author.
(<class 'custom_components.acv.sensor.WasteTypeSensor'>) implements device_state_attributes. Please report it to the custom component author.
(<class 'custom_components.acv.sensor.WasteTypeSensor'>) implements device_state_attributes. Please report it to the custom component author.

**Comment by Cadsters** [comment]
Fixed in v0.24.3 please upgrade.

**Comment by iObi** [comment]
Thank you
