### ISSUE TITLE
Language selection (request)

### ISSUE THREAD

**Issue by jvandergeer** [Cadsters/acv-hass-component#8]
Hi,

would it be possible to integrate language selection for this component? It's a mix between Dutch and English now. I'd like to be able to choose either of those for my frontend.

Thank you.

**Comment by Cadsters** [comment]
I don't see the point, what should be in dutch/english? 
The integration is targeted towards dutch users so the sensor-names are in dutch. 
Homeassistant is an english platform thats why the description what the integration is about is in english.
Offcource you are most welcome to create a pull request with your addition to the code.

**Comment by jvandergeer** [comment]
Not all Dutch people have their interfaces in Dutch ;)
And of course there's a lot of non-Dutch-speaking people living in The
Netherlands...

Op zo 26 apr. 2020 om 23:42 schreef Cadsters <notifications@github.com>:
