### ISSUE TITLE
Mogelijkheid tot formaat datum wijzigen

### ISSUE THREAD

**Issue by evanlaar01** [Cadsters/acv-hass-component#9]
Daar dit een Nederlandse addon is, maar in het Nederlands :-)
Is het mogelijk om het formaat datum aan te passen? Nu staat er bijvoorbeeld: 2020-12-08.
Ik heb het proberen aan te passen in de sensor.py door alle %Y %m %d te vervangen door %d %m %Y maar dat werkt niet.
Alvast dank en topwerk!

**Comment by Cadsters** [comment]
Look [here](https://github.com/Cadsters/acv-hass-component/issues/1#issuecomment-523004293)
